version: '3.8'

services:
  postgres:
    image: postgres:12.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mindminder-pqsl-dev
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: always
volumes:
  database-data: